create table if not exists public.freezer_history (
  id bigint generated by default as identity primary key,
  slot_id text not null,
  old_occupant text not null default '',
  new_occupant text not null default '',
  changed_at timestamptz not null default timezone('utc', now()),
  constraint freezer_history_slot_id_format check (slot_id ~ '^L[1-4]-C[1-5]-H[1-5]-D[1-4]$')
);

create index if not exists freezer_history_changed_at_idx
  on public.freezer_history (changed_at desc);
create index if not exists freezer_history_slot_id_idx
  on public.freezer_history (slot_id, changed_at desc);

alter table public.freezer_history enable row level security;

drop policy if exists "Freezer history is publicly readable" on public.freezer_history;
create policy "Freezer history is publicly readable"
on public.freezer_history for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.freezer_history from anon, authenticated;
grant select on public.freezer_history to anon, authenticated;

create or replace function public.update_freezer_slot(
  p_id text,
  p_occupant text,
  p_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  cleaned_occupant text := btrim(coalesce(p_occupant, ''));
  previous_occupant text := '';
begin
  if encode(digest(coalesce(p_code, ''), 'sha256'), 'hex') <> 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3' then
    raise exception 'invalid_edit_code';
  end if;

  if p_id !~ '^L[1-4]-C[1-5]-H[1-5]-D[1-4]$' then
    raise exception 'invalid_freezer_position';
  end if;

  if char_length(cleaned_occupant) > 80 then
    raise exception 'occupant_label_too_long';
  end if;

  select occupant into previous_occupant
  from public.freezer_slots
  where id = p_id;
  previous_occupant := coalesce(previous_occupant, '');

  insert into public.freezer_slots (id, occupant, updated_at)
  values (p_id, cleaned_occupant, timezone('utc', now()))
  on conflict (id) do update
    set occupant = excluded.occupant,
        updated_at = excluded.updated_at;

  if previous_occupant is distinct from cleaned_occupant then
    insert into public.freezer_history (slot_id, old_occupant, new_occupant, changed_at)
    values (p_id, previous_occupant, cleaned_occupant, timezone('utc', now()));
  end if;

  return jsonb_build_object('ok', true, 'id', p_id, 'occupant', cleaned_occupant);
end;
$$;

revoke all on function public.update_freezer_slot(text, text, text) from public;
grant execute on function public.update_freezer_slot(text, text, text) to anon, authenticated;
